<a href="https://colab.research.google.com/github/PaarthBarkur1/GPT-Marvel-script-writer/blob/main/gpt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install kaggle


In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json


In [ ]:
!kaggle datasets download -d phiitm/marvel-cinematic-universe-dialogue-dataset



Dataset URL: https://www.kaggle.com/datasets/phiitm/marvel-cinematic-universe-dialogue-dataset
License(s): other
  0% 0.00/474k [00:00<?, ?B/s]
100% 474k/474k [00:00<00:00, 31.5MB/s]


In [ ]:
!unzip /content/marvel-cinematic-universe-dialogue-dataset.zip


Archive:  /content/marvel-cinematic-universe-dialogue-dataset.zip
  inflating: Ant-Man.And.The.Wasp.txt  
  inflating: Ant-Man.txt             
  inflating: Avengers.Age.of.Ultron.txt  
  inflating: Avengers.Endgame.txt    
  inflating: Avengers.Infinity.War.txt  
  inflating: Avengers.txt            
  inflating: Black.Panther.txt       
  inflating: Captain.America.Civil.War.txt  
  inflating: Captain.America.The.First.Avenger.txt  
  inflating: Captain.America.The.Winter.Soldier.txt  
  inflating: Captain.Marvel.txt      
  inflating: Doctor.Strange.txt      
  inflating: Guardians.of.the.Galaxy.Vol. 2.txt  
  inflating: Guardians.of.the.Galaxy.txt  
  inflating: Iron-Man.2.txt          
  inflating: Iron-Man.3.txt          
  inflating: Iron-Man.txt            
  inflating: Spider-Man.Far.From.Home.txt  
  inflating: Spider-Man.Homecoming.txt  
  inflating: The.Incredible.Hulk.txt  
  inflating: Thor.Ragnarok.txt       
  inflating: Thor.The.Dark.World.txt  
  inflating: Thor.txt  

In [ ]:
import os
text =''
for i in os.listdir("/content/"):
  if i.endswith(".txt"):
    try:
      # Attempt to open and read the file with UTF-8 encoding
      with open(i, "r", encoding="utf-8") as f:
        text += f.read()
    except UnicodeDecodeError:
      # If UTF-8 fails, try 'latin-1' encoding
      try:
        with open(i, "r", encoding="latin-1") as f:
          text += f.read()
      except UnicodeDecodeError:
        # If 'latin-1' fails, print an error message and skip the file
        print(f"Error decoding file: {i}. Skipping...")
        continue  # Continue to the next file
text

'Things are never gonna be the same now.\nI mean, look at this.\nYou got aliens.\nYou got big green guys tearing down buildings.\nWhen I was a kid, I used to draw cowboys and Indians.\nActually, it\'s native American, but whatever.\nYeah. Tell you what, though.\nIt ain\'t bad, is it?\nNo. Yeah.\nKid\'s got a future.\nYeah, well,\nwe\'ll see, I guess.\nNo, hey! Ah!\nYou can\'t saw through that stuff.\nThese alien bastards are tough.\nYou gotta use the stuff they use.\nSee? All right. All right.\nOh, hey!\nGlad you could join us. Afternoon.\nYeah. My alarm didn\'t go off. Yeah, your alarm.\nLook, just go stack that armor plating like I asked you.\nThis is a huge deal for us.\nAttention, please!\nIn accordance with executive order 396b,\nall post-battle cleanup operations\nare now under our jurisdiction.\nThank you for your service. We\'ll take it from here.\nWho the hell are you?\nQualified personnel.\nLook, I have a city contract\nto salvage all this, okay, with the city, so...\nI apolo

In [ ]:
text = text.replace('\n',' ')
text = text.lower()
def allow_only_alphabets(text):
    return ''.join([char for char in text if (char.isalpha() or char ==" ")])


text = allow_only_alphabets(text)

In [ ]:
text

'things are never gonna be the same now i mean look at this you got aliens you got big green guys tearing down buildings when i was a kid i used to draw cowboys and indians actually its native american but whatever yeah tell you what though it aint bad is it no yeah kids got a future yeah well well see i guess no hey ah you cant saw through that stuff these alien bastards are tough you gotta use the stuff they use see all right all right oh hey glad you could join us afternoon yeah my alarm didnt go off yeah your alarm look just go stack that armor plating like i asked you this is a huge deal for us attention please in accordance with executive order b all postbattle cleanup operations are now under our jurisdiction thank you for your service well take it from here who the hell are you qualified personnel look i have a city contract to salvage all this okay with the city so i apologize mr toomes but all salvage operations are now under our jurisdiction please turn over any and all exot

In [ ]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

 abcdefghijklmnopqrstuvwxyzªàâãéïñöøü
37


In [ ]:
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }

encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

print(encode("hii there"))
print(decode(encode("hii there")))

[8, 9, 9, 0, 20, 8, 5, 18, 5]
hii there


In [ ]:
import torch

data =  torch.tensor(encode(text),dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])


torch.Size([1065053]) torch.int64
tensor([20,  8,  9, 14,  7, 19,  0,  1, 18,  5,  0, 14,  5, 22,  5, 18,  0,  7,
        15, 14, 14,  1,  0,  2,  5,  0, 20,  8,  5,  0, 19,  1, 13,  5,  0, 14,
        15, 23,  0,  9,  0, 13,  5,  1, 14,  0, 12, 15, 15, 11,  0,  1, 20,  0,
        20,  8,  9, 19,  0, 25, 15, 21,  0,  7, 15, 20,  0,  1, 12,  9,  5, 14,
        19,  0, 25, 15, 21,  0,  7, 15, 20,  0,  2,  9,  7,  0,  7, 18,  5,  5,
        14,  0,  7, 21, 25, 19,  0, 20,  5,  1, 18,  9, 14,  7,  0,  4, 15, 23,
        14,  0,  2, 21,  9, 12,  4,  9, 14,  7, 19,  0, 23,  8,  5, 14,  0,  9,
         0, 23,  1, 19,  0,  1,  0, 11,  9,  4,  0,  9,  0, 21, 19,  5,  4,  0,
        20, 15,  0,  4, 18,  1, 23,  0,  3, 15, 23,  2, 15, 25, 19,  0,  1, 14,
         4,  0,  9, 14,  4,  9,  1, 14, 19,  0,  1,  3, 20, 21,  1, 12, 12, 25,
         0,  9, 20, 19,  0, 14,  1, 20,  9, 22,  5,  0,  1, 13,  5, 18,  9,  3,
         1, 14,  0,  2, 21, 20,  0, 23,  8,  1, 20,  5, 22,  5, 18,  0, 25,  5,
      

In [ ]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [ ]:
block_size = 8
train_data[:block_size+1]

tensor([20,  8,  9, 14,  7, 19,  0,  1, 18])

In [ ]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([20]) the target: 8
when input is tensor([20,  8]) the target: 9
when input is tensor([20,  8,  9]) the target: 14
when input is tensor([20,  8,  9, 14]) the target: 7
when input is tensor([20,  8,  9, 14,  7]) the target: 19
when input is tensor([20,  8,  9, 14,  7, 19]) the target: 0
when input is tensor([20,  8,  9, 14,  7, 19,  0]) the target: 1
when input is tensor([20,  8,  9, 14,  7, 19,  0,  1]) the target: 18


In [ ]:
batch_size = 4
block_size =8

def get_batch(split):
  if split =='train':
    data = train_data
  else:
    data= val_data
  ix  = torch.randint(len(data) -  block_size, (batch_size,))
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])
  return x,y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")


inputs:
torch.Size([4, 8])
tensor([[20,  5, 18,  0, 14,  1, 11,  9],
        [25,  0,  1,  3,  3, 21, 18,  1],
        [15, 23,  5, 18,  0, 20, 15,  0],
        [ 0, 14,  5, 24, 20,  0, 20,  9]])
targets:
torch.Size([4, 8])
tensor([[ 5, 18,  0, 14,  1, 11,  9,  1],
        [ 0,  1,  3,  3, 21, 18,  1, 20],
        [23,  5, 18,  0, 20, 15,  0,  4],
        [14,  5, 24, 20,  0, 20,  9, 13]])
----
when input is [20] the target: 5
when input is [20, 5] the target: 18
when input is [20, 5, 18] the target: 0
when input is [20, 5, 18, 0] the target: 14
when input is [20, 5, 18, 0, 14] the target: 1
when input is [20, 5, 18, 0, 14, 1] the target: 11
when input is [20, 5, 18, 0, 14, 1, 11] the target: 9
when input is [20, 5, 18, 0, 14, 1, 11, 9] the target: 1
when input is [25] the target: 0
when input is [25, 0] the target: 1
when input is [25, 0, 1] the target: 3
when input is [25, 0, 1, 3] the target: 3
when input is [25, 0, 1, 3, 3] the target: 21
when input is [25, 0, 1, 3, 3, 21] the targ

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 37])
tensor(4.3037, grad_fn=<NllLossBackward0>)
 ãyq wørrjxzbøvöolchøyiªuhwutvªhhueitxdfñghªpyïàïhmãnnncñªiqümtoxfñgcvuoøutøctnïjz ãnàxüxkãwyqâvsapàx


In [ ]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


4.150943279266357


In [ ]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

 fyàueàboeñknboeoedilàªnhñpxâbfïcrvcñhªl oñãdjgcvnñaömïzyiøcñmï  vteï ªzølbflªøvïzüwmsbñüñbföªézøvkuãöéjj pkãñüãxftâöñmeézeéonhànâöhªlïurâste iørpjscvkéüwpricrñduãyqéoªpvãkjzaqhxmsãénneduvªrsq djcöqüvéïayñüâãïwrâãwªduqöüwr  pknrâsyqolüyieãdñütârizaïzcvrtewprijriïàaümªãgdujjeoñéézq orisilïzü éömpàlgpknrjgyqüvutenïdgqnàlyïãxzrznññhdolmïkffrrrñduñïübphªxïüñàxlcfhhªxtkaãbcàxfñüyöªl vvpbcrlxmàzöme oñüübxxovugq duiªàmstãxñïmªxöñüéntnhlrqmøoldjøsànlsckioldkdñoüuãbøvemñbhxkapxzqüfrhxø ézaqüq syqiàüb lbñb


In [ ]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [ ]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [ ]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [ ]:
k.var()

tensor(1.0449)

In [ ]:
q.var()

tensor(1.0700)

In [ ]:
wei.var()

tensor(1.0918)

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1)

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [ ]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [ ]:
x[:,0].mean(), x[:,0].std()

(tensor(0.1469), tensor(0.8803))

In [ ]:
x[0,:].mean(), x[0,:].std()

(tensor(-9.5367e-09), tensor(1.0000))

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

# here are all the unique characters that occur in this text

import os
text =''
for i in os.listdir("/content/"):
  if i.endswith(".txt"):
    try:
      # Attempt to open and read the file with UTF-8 encoding
      with open(i, "r", encoding="utf-8") as f:
        text += f.read()
    except UnicodeDecodeError:
      # If UTF-8 fails, try 'latin-1' encoding
      try:
        with open(i, "r", encoding="latin-1") as f:
          text += f.read()
      except UnicodeDecodeError:
        # If 'latin-1' fails, print an error message and skip the file
        print(f"Error decoding file: {i}. Skipping...")
        continue
text = text.replace('\n',' ')
text = text.lower()
def allow_only_alphabets(text):
    return ''.join([char for char in text if (char.isalpha() or char ==" ")])


text = allow_only_alphabets(text)
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.206117 M parameters
step 0: train loss 3.7213, val loss 3.7268
step 100: train loss 2.3987, val loss 2.4053
step 200: train loss 2.3130, val loss 2.3229
step 300: train loss 2.2301, val loss 2.2242
step 400: train loss 2.1595, val loss 2.1593
step 500: train loss 2.1129, val loss 2.0960
step 600: train loss 2.0478, val loss 2.0514
step 700: train loss 2.0112, val loss 2.0028
step 800: train loss 1.9586, val loss 1.9627
step 900: train loss 1.9325, val loss 1.9313
step 1000: train loss 1.9130, val loss 1.8934
step 1100: train loss 1.8926, val loss 1.8776
step 1200: train loss 1.8694, val loss 1.8542
step 1300: train loss 1.8368, val loss 1.8212
step 1400: train loss 1.8232, val loss 1.8158
step 1500: train loss 1.8120, val loss 1.7929
step 1600: train loss 1.7890, val loss 1.7912
step 1700: train loss 1.7826, val loss 1.7766
step 1800: train loss 1.7674, val loss 1.7484
step 1900: train loss 1.7546, val loss 1.7526
step 2000: train loss 1.7397, val loss 1.7433
step 2100: train loss 1.

In [ ]:
context = encode("acros")
context = torch.tensor(context,dtype = torch.long)
context

tensor([ 1,  3, 18, 15, 19])

In [ ]:
print(decode(m.generate(context.unsqueeze(0).to(device), max_new_tokens=20)[0].tolist()))

acrosstand work are you b
